### ISSUE TITLE
Duplicate BuildArch entry

### ISSUE THREAD

**Issue by rguhr** [koss822/misc#4]
BuildArch is double defined with different options
https://github.com/koss822/misc/blob/7fb1213d4fb63b56bafd9873322ab9f4f06b485e/Linux/Projects/dante_socks/rpmbuild/SPECS/sockd.spec#L5-L8

which leads to following error
```
$ rpmbuild --version
RPM version 4.15.1

$ rpmbuild -bb --define "_topdir ${PWD}" SPECS/sockd.spec  
error: line 8: Duplicate BuildArch entry: BuildArch:      noarch
```

**Comment by koss822** [comment]
thank you for noticing, I have fixed code
